services:
  dev_frontend:
    container_name: dev_frontend
    hostname: dev-frontend
    build: frontend
    restart: always
    ports:
      - 9090:80
    #command: bash -c "tail -f /dev/null" # for debug only
  dev_backend:
    container_name: dev_backend
    hostname: dev-backend
    build: backend
    restart: always
    environment:
      - SERVER_PORT=8080
      - SUBD_HOST=dev_postgres
      - SUBD_PORT=5432
      - SUBD_DB=db
      - SUBD_USER=pguser
      - SUBD_PASS=pgPass
      - PASSWORD_HASH_SALT_OR_ROUNDS=15
      - JWT_SECRET=dfgergergergergreg
      - JWT_EXPIRES_IN=9h
    #command: bash -c "tail -f /dev/null" # for debug only
  dev_postgres:
    container_name: dev_postgres
    hostname: dev-postgres
    build: postgres
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgPass
      - POSTGRES_DB=db
    ports:
      - 5433:5432
    volumes:
      - dev_pg_data:/var/lib/postgresql/data
volumes:
  dev_pg_data: